---
pagetitle: EC2208 Econometrics 1
output: 
  revealjs::revealjs_presentation:
    incremental: false
    theme: solarized
    self_contained: false
    reveal_plugins: ["chalkboard"]
    # reveal_plugins: ["menu"]
    highlight: pygments
    center: true
    transition: none
    background_transition: none 
    reveal_options:
      chalkboard:
        theme: whiteboard
        toggleNotesButton: true
        toggleChalkboardButton: true
      # menu:
      #   numbers: true
      # slideNumber: true
      # previewLinks: false
    fig_caption: true
    pandoc_args:
    - --indented-code-classes
    - lineNumbers
    css: mystyle.css
    
--- 

<section>

<h1>EC2208 Econometrics 1</h1>

<br>

<h2>[Jesper Bagger](mailto:jesper.bagger@rhul.ac.uk)</h2>

<h3>EC2208 | Royal Holloway | 2021/22</h3>

</section>


# Aims

- Further your knowledge of the **statistical theory** and the **application** of regression analysis to answer **quantitative questions** relevant to business and government policy

- Improve your proficiency with the statistical language **R** 

# Learning outcomes

- Understand the statistical properties of the OLS estimator in the linear regression model

<!-- - Critically assess the appropriateness of the OLS estimator to answer a given question -->

- Be able to formulate hypotheses in the context of the linear regression model and carry out  statistical tests

- Be able to manipulate datasets using R

- Be able to implement linear regression analysis using R

- Be able to interpret regression output from R

# Week 1-5: cross section data

1. Revisit OLS in the simple linear regression model

2. Goodness of fit, OLS properties

3. Hypotheses testing (simple hypotheses)

4. The multiple linear regression model

5. Hypotheses testing (joint hypotheses)

# Week 6-10: time series data

6. Autocovariance and stationarity

7. Autoregressions

8. Autoregressive Distributed Lag models

9. Trends

10. Breaks

# Textbook(s)

**Main text**

Stock, James H. and Mark W. Watson, *Introduction to Econometrics*, 4th Edn. (Global Edn.), 2020, Pearson 

(earlier editions are also suitable)

**Companion text**

Hanck, Christoph, Martin Arnold, Alexander Gerber, and Martin Schmelzer, *Introduction to Econometrics with R*, 2020, 

([e-text](https://www.econometrics-with-r.org/))

# Assessment

- Final Exam (60%)

- Graded homework I (20%)

- Graded homework II (20%)

Weekly homework submission (deadline: Tuesdays, 11:59am)

Graded homework I chosen among week 1-5 homeworks 

Graded homework II chosen among week 6-10 homeworks

# R with RStudio

R is a language and environment for statistical computing and graphics; it is **free** and **open source**.

RStudio is a development environment for R. We shall use the **free**, **open source** version of RStudio. 

R is used widely in both academia, and the worlds of business and government: mastering R is a **valuable skill**.
